version: '3.8'

services:
  vilg:
    build:
      context: .
      dockerfile: Dockerfile.vilg
      target: final
    image: vision-language-grasping-final
    container_name: vilg-app
    volumes:
      - ./:/app
      - ./assets:/app/assets
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
      - PYTHONPATH=/app:/app/models/graspnet/pointnet2:/app/models/graspnet/knn
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      sh -c "
      echo 'Python version:' && python --version &&
      echo 'Pip list:' && pip list &&
      echo 'PYTHONPATH:' && echo $$PYTHONPATH &&
      echo 'Contents of /app/models/graspnet/pointnet2:' && ls -R /app/models/graspnet/pointnet2 &&
      echo 'Trying to import pointnet2._ext:' && python -c 'import pointnet2._ext; print(\"Successfully imported pointnet2._ext\")' &&
      echo 'Running test.py:' && python3 scripts/test.py
      "

  pip-compile:
    build:
      context: .
      dockerfile: Dockerfile.pip-compile
    volumes:
      - ./:/app
      - ./:/output
    environment:
      - SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True