version: '3.8'

services:
  pip-compile:
    build:
      context: .
      dockerfile: Dockerfile.pip-compile
    volumes:
      - ./:/app
      - ./:/output
    environment:
      - SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
  vilg:
    build:
      context: .
      dockerfile: Dockerfile.vilg
      target: final
    image: vision-language-grasping-final
    container_name: vilg-app
    volumes:
      - ./:/app
      - ./assets:/app/assets
      - /tmp/.X11-unix:/tmp/.X11-unix
      - vilg_debug:/debug_output
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
      - PYTHONPATH=/app:/app/models/graspnet:/app/models/graspnet/pointnet2:/app/models/graspnet/knn:/usr/local/lib/python3.8/dist-packages
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      bash -c "
      echo 'Debug output:' &&
      /app/debug.sh &&
      echo 'Running main script:' &&
      python3 scripts/test.py
      "
volumes:
  vilg_debug: