version: '3.8'

services:
  pip-compile:
    build:
      context: .
      dockerfile: Dockerfile.pip-compile
    volumes:
      - ./:/app
      - ./:/output
    environment:
      - SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True

  vilg:
    build:
      context: .
      dockerfile: Dockerfile.vilg
      target: final_with_opengl
    image: vision-language-grasping-final
    container_name: vilg-app
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
      - PYTHONPATH=/app:/app/models/graspnet:/app/models/graspnet/pointnet2:/app/models/graspnet/pointnet2/build/lib.linux-x86_64-cpython-38:/app/models/graspnet/knn:/usr/local/lib/python3.8/dist-packages
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./:/app
      - ./assets:/app/assets
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - vilg_debug:/debug_output
      - ./models/graspnet/pointnet2/build/lib.linux-x86_64-cpython-38/pointnet2:/app/models/graspnet/pointnet2/build/lib.linux-x86_64-cpython-38/pointnet2
      - $HOME/.Xauthority:/root/.Xauthority:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      bash -c "
      echo 'Debug output:' &&
      ls -l /app/models/graspnet/pointnet2/ &&
      echo 'Python path:' &&
      python -c 'import sys; print(sys.path)' &&
      echo 'Pointnet2 location:' &&
      python -c 'import pointnet2; print(pointnet2.__file__)' || echo 'Failed to import pointnet2' &&
      echo 'Pointnet2._ext location:' &&
      python -c 'from pointnet2 import _ext; print(_ext.__file__)' || echo 'Failed to import pointnet2._ext' &&
      echo 'Contents of /app/models/graspnet/pointnet2:' &&
      ls -R /app/models/graspnet/pointnet2 &&
      echo 'Contents of /usr/local/lib/python3.8/dist-packages/pointnet2*:' &&
      ls -R /usr/local/lib/python3.8/dist-packages/pointnet2* &&
      echo 'Contents of /app/models/graspnet/pointnet2/__init__.py:' &&
      cat /app/models/graspnet/pointnet2/__init__.py &&
      echo 'Running main script:' &&
      python3 scripts/test.py
      "
volumes:
  vilg_debug: