version: '3.8'

services:
  pip-compile:
    build:
      context: .
      dockerfile: Dockerfile.pip-compile
    volumes:
      - ./:/app
      - ./:/output
    environment:
      - SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
  vilg:
    build:
      context: .
      dockerfile: Dockerfile.vilg
      target: final
    image: vision-language-grasping-final
    container_name: vilg-app
    volumes:
      - ./:/app
      - ./assets:/app/assets
      - /tmp/.X11-unix:/tmp/.X11-unix
      - vilg_debug:/debug_output
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True
      - PYTHONPATH=/app:/app/models/graspnet/pointnet2:/app/models/graspnet/knn
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      sh -c "
      echo 'Starting debug...' > /debug_output/debug.log &&
      python --version >> /debug_output/debug.log 2>&1 &&
      pip list >> /debug_output/debug.log 2>&1 &&
      echo $$PYTHONPATH >> /debug_output/debug.log &&
      ls -R /app/models/graspnet/pointnet2 >> /debug_output/debug.log 2>&1 &&
      python -c 'import torch; print(torch.__version__, torch.cuda.is_available())' >> /debug_output/debug.log 2>&1 &&
      echo 'Debug complete. Starting main script...' >> /debug_output/debug.log &&
      python3 scripts/test.py
      "
volumes:
  vilg_debug: